# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue May  7 05:29:00 2024
# ------------------------------------------------

package:
  name: transformers
  version: 4.40.2
source:
  sha256: 657b6054a2097671398d976ad46e60836e7e15f9ea9551631a96e33cb9240649
  url: https://pypi.io/packages/source/t/transformers/transformers-4.40.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/transformers_1715059825623/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h55db66e_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.3 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.3.0 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.5.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - datasets !=2.5.0
    - filelock
    - huggingface_hub >=0.19.3,<1.0
    - numpy >=1.17
    - packaging >=20.0
    - python >=3.8
    - pyyaml >=5.1
    - regex !=2019.12.17
    - requests
    - safetensors >=0.4.1
    - tokenizers >=0.19,<0.20
    - tqdm >=4.27
test:
  commands:
    - transformers-cli --help
  imports:
    - transformers
    - transformers.benchmark
    - transformers.commands
    - transformers.data
    - transformers.kernels
    - transformers.models
    - transformers.pipelines
    - transformers.tools
    - transformers.utils
about:
  doc_url: https://huggingface.co/transformers/
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240507.2.1
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
    - roccqqck
    - setu4993
  remote_url: https://github.com/conda-forge/transformers-feedstock
  sha: 178f591fae11f48335138cafbbfce943c1f1facf
